language: c

os:
  - linux
  # - osx

matrix:
  include:
    - os: linux
      env: VALGRIND="/usr/bin/valgrind --leak-check=full --error-exitcode=1"
      compiler: gcc
    - os: osx
      env: VALGRIND=""
      compiler: clang

# compiler:
#   - clang
#   - gcc

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ];
      then brew update;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ];
      then brew install doxygen;
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ];
      then sudo apt-get install -y valgrind;
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ];
      then sudo apt-get install -y doxygen;
    fi

script:
  - make clean dev
  # - if [ "$TRAVIS_OS_NAME" = "linux" ];
  #     then valgrind --leak-check=full --error-exitcode=1 tests/entity_tests;
  #   fi
  - make tests
  - make clean all
  - make docs
