language: c
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get install -y doxygen
  - sudo apt-get install -y valgrind
script:
  - make clean all
  - env VALGRIND="$(which valgrind) --leak-check=full --error-exitcode=1" make
    tests
  - make docs
