language: c

os:
  - linux
  # - osx

compiler:
  - clang
  - gcc

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install doxygen; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ];
    then sudo apt-get install -y valgrind; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ];
    then sudo apt-get install -y doxygen; fi

script:
  - echo "$TRAVIS_OS_NAME"
  - make clean all
  - if [ "$TRAVIS_OS_NAME" = "linux" ];
    then env VALGRIND="$(which valgrind) --leak-check=full --error-exitcode=1"
    make tests; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then make tests; fi
  - make docs
