title: pixhdl
email: kokkonisd@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A command-line tool that produces graphical representations of entities from VHDL source files.
baseurl: "/pixhdl" # the subpath of your site, e.g. /blog
url: "https://kokkonisd.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jimkokko5
github_username:  kokkonisd

# Build settings
markdown: kramdown
highlighter: rouge
